### ISSUE TITLE
Layout not handled

### ISSUE THREAD

**Issue by Davounet** [maizzle/starter-api#1]
Hello !
I am trying to use maizzle through nodejs, and your repo was really helpfull !
One problem appeared though, the components of the email (layout included) are not parsed by maizzle.
For example, if you clone this repo and build the email, the `hidden` class for the preheader is not handled, which results in it being visible in the built email.
I guess there is a configuration to be passed to maizzle to handle the external files (the initial template is handled fine) but I fail to find a working combination.
I would be really grateful if you could stear me in the right direction !
Have a nice day

**Comment by cossssmin** [comment]
Hey sorry for missing this!

You'd need to configure Tailwind to not purge classes from the layout. See #2 but keep in mind that's for Maizzle 4.0, for 3.x you'll need to use the old purging strategy ([see v3 docs](https://maizzle.com/docs/tailwindcss/#css-purging)).
